spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        message-in:
          destination: messages
          contentType: application/json
        message-out:
          destination: messages
          contentType: application/json